<?php

use App\Http\ApiV1\Modules\Users\Controllers\UsersController;

$generatedRoutes = __DIR__ . "/OpenApiGenerated/routes.php";
if (file_exists($generatedRoutes)) { // prevents your app and artisan from breaking if there is no autogenerated Route file for some reason.
    require $generatedRoutes;
}

 Route::post('users/test', [UsersController::class, 'test']); 
 Route::post('users/login', [UsersController::class, 'login']); 
 Route::post('users/register', [UsersController::class, 'register']); 
 Route::group(['middleware' => 'auth:api'], function()
 { 
        Route::post('users/user-details', [UsersController::class, 'userDetails']); 
});