<?php

use App\Http\ApiV1\Modules\Users\Controllers\UsersController;
use App\Http\ApiV1\Modules\Users\Controllers\CommentsController;
use App\Http\ApiV1\Modules\Users\Controllers\EnrollmentsController;
use App\Http\ApiV1\Modules\Users\Controllers\ReviewsController;
use App\Http\ApiV1\Modules\Users\Controllers\StepsController;

$generatedRoutes = __DIR__ . "/OpenApiGenerated/routes.php";
if (file_exists($generatedRoutes)) { // prevents your app and artisan from breaking if there is no autogenerated Route file for some reason.
    require $generatedRoutes;
}

Route::group(['prefix' => 'users'], function () {
    Route::post('/test', [UsersController::class, 'test']); 
    Route::post('/login', [UsersController::class, 'login']); 
    Route::post('/register', [UsersController::class, 'register']); 
    Route::group(['middleware' => 'auth:api'], function()
    { 
        Route::post('/details', [UsersController::class, 'userDetails']); 
    });
});

Route::group(['prefix' => 'comments'], function () {
    Route::get('/{id}', [CommentsController::class, 'get']);
    Route::post('/', [CommentsController::class, 'add']); 
    Route::delete('/{id}', [CommentsController::class, 'delete']);
});

Route::group(['prefix' => 'enrollments'], function () {
    Route::get('/{id}', [EnrollmentsController::class, 'get']); 
    Route::get('/by_user/{id}', [EnrollmentsController::class, 'getByUserId']); 
    
    Route::post('/', [EnrollmentsController::class, 'add']); 
    Route::delete('/{id}', [EnrollmentsController::class, 'delete']); 
});

Route::group(['prefix' => 'reviews'], function () {
    Route::get('/{id}', [ReviewsController::class, 'get']); 
    Route::post('/', [ReviewsController::class, 'add']); 
    Route::delete('/{id}', [ReviewsController::class, 'delete']); 
});

Route::group(['prefix' => 'steps'], function () {
    Route::get('/{id}', [ReviewsController::class, 'get']); 
    Route::post('/', [ReviewsController::class, 'add']); 
    Route::delete('/{id}', [ReviewsController::class, 'delete']); 
});